<?php

namespace Tests\Unit\AutoTest\Util;

use PHPUnit\Framework\TestCase;
use TRF4\UI\Util\Autocomplete\Multi\ArrayOfObjects;
use TRF4\UI\Util\Autocomplete\Multi\ArrayOfStrings;
use TRF4\UI\Util\Autocomplete\Multi\Map;
use TRF4\UI\Util\Autocomplete\Multi\NullObject;
use TRF4\UI\Util\Autocomplete\MultiObjectFactory;

class MultiAutocompleteObjectFactoryTest extends TestCase
{
    /** @var array */
    public $requestData;


    protected function setUp(): void
    {
        $this->requestData = [
            'ac1_value_map' => [
                3 => 'Paraná'
            ],
            'ac2_value' => [
                1 => [
                    'code' => 1,
                    'name' => 'RS'
                ]

            ],
            'ac3_value' => [
                'RS' => '',
                'SC' => ''
            ]
        ];

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @dataProvider dpTest
     */
    public function test($namePrefix, $expectedClass)
    {
        $actual = MultiObjectFactory::create($namePrefix, $this->requestData);
        $this->assertInstanceOf($expectedClass, $actual);
    }

    public function dpTest()
    {
        return [
            ['ac1', Map::class],
            ['ac2', ArrayOfObjects::class],
            ['ac3', ArrayOfStrings::class],
            ['ac4', NullObject::class]
        ];
    }

    /**
     * @dataProvider dpTestValues
     */
    public function testGetValues($namePrefix, $expectedValues)
    {
        $acObject = MultiObjectFactory::create($namePrefix, $this->requestData);
        $this->assertEquals($expectedValues, $acObject->values());
    }

    public function dpTestValues()
    {
        return [
            ['ac1', [3]],
            ['ac2', [1]],
            ['ac3', ['RS', 'SC']],
            ['ac4', []]
        ];
    }

    /**
     * @dataProvider dpTestObjects
     */
    public function testGetObjects($namePrefix, $expectedValues)
    {
        $acObject = MultiObjectFactory::create($namePrefix, $this->requestData);
        $this->assertEquals($expectedValues, $acObject->objects());
    }

    public function dpTestObjects()
    {
        return [
            [
                'ac1', [
                3 => 'Paraná'
            ]
            ], [
                'ac2',
                [
                    [
                        'code' => 1,
                        'name' => 'RS'
                    ]
                ]
            ], [
                'ac3', ['RS', 'SC']
            ],
            [
                'ac4', []
            ]
        ];
    }

}
