version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_XDEBUG: $INSTALL_XDEBUG
        XDEBUG_VERSION: 2.9.2
        PHP_VERSION: 7.3
    user: 1000:1000
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - .:/var/www/myapp
    networks:
      - sdnet

  workspace:
    build:
      context: .docker/workspace
      args:
        PHP_VERSION: 7.3
        NODE_VERSION: 16.13.0
        COMPOSER_VERSION: 2.1.12
        PYTHON_VERSION: 2.7
        XDEBUG_VERSION: 2.7.0
        INSTALL_XDEBUG: $INSTALL_XDEBUG
    user: 1000:1000
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      COMPOSER_AUTH: '{"gitlab-oauth":{"git.trf4.jus.br":"${COMPOSER_AUTH}"}}'
    volumes:
      - .:/usr/src/myapp
    entrypoint: [ "sh", "-c" ]
    command: [ "
      make build-dev &
      tail -f /dev/null
    " ]
    networks:
      - sdnet

  selenium:
    image: selenium/standalone-chrome:88.0
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - server
    volumes:
      - /dev/shm:/dev/shm
    links:
      - server:sdnet.test
    networks:
      - sdnet


volumes:
  composer-cache:
    external: false

networks:
  sdnet:
