<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'N98\\JUnitXml' => array($vendorDir . '/n98/junit-xml/src'),
    'JsonMapper' => array($vendorDir . '/netresearch/jsonmapper/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Dissect' => array($vendorDir . '/jakubledl/dissect/src'),
    'Dflydev\\DotAccessData' => array($vendorDir . '/dflydev/dot-access-data/src'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
    'AspectMock' => array($vendorDir . '/codeception/aspect-mock/src'),
);
