<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'app',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '9a9580fa1c0429ed45b06dc8f6aeaa936949c277',
        'name' => 'trf4/eproc',
        'dev' => true,
    ),
    'versions' => array(
        'aws/aws-crt-php' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-crt-php',
            'aliases' => array(),
            'reference' => '3942776a8c99209908ee0b287746263725685732',
            'dev_requirement' => false,
        ),
        'aws/aws-sdk-php' => array(
            'pretty_version' => '3.222.12',
            'version' => '3.222.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-sdk-php',
            'aliases' => array(),
            'reference' => '8503d393b3ebef20241931b1abc20cb2af494cb2',
            'dev_requirement' => false,
        ),
        'behat/gherkin' => array(
            'pretty_version' => 'v4.9.0',
            'version' => '4.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/gherkin',
            'aliases' => array(),
            'reference' => '0bc8d1e30e96183e4f36db9dc79caead300beff4',
            'dev_requirement' => true,
        ),
        'bluem/tree' => array(
            'pretty_version' => '3.2',
            'version' => '3.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bluem/tree',
            'aliases' => array(),
            'reference' => '2369895e54397115e99252dde42d929897d6dbc4',
            'dev_requirement' => false,
        ),
        'brainmaestro/composer-git-hooks' => array(
            'pretty_version' => 'v2.8.5',
            'version' => '2.8.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brainmaestro/composer-git-hooks',
            'aliases' => array(),
            'reference' => 'ffed8803690ac12214082120eee3441b00aa390e',
            'dev_requirement' => true,
        ),
        'cocur/slugify' => array(
            'pretty_version' => 'v3.2',
            'version' => '3.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cocur/slugify',
            'aliases' => array(),
            'reference' => 'd41701efe58ba2df9cae029c3d21e1518cc6780e',
            'dev_requirement' => false,
        ),
        'codeception/aspect-mock' => array(
            'pretty_version' => '4.1.1',
            'version' => '4.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/aspect-mock',
            'aliases' => array(),
            'reference' => 'b15254b7d2a9641bbb2ae7794220e72fa2e2b37d',
            'dev_requirement' => true,
        ),
        'codeception/codeception' => array(
            'pretty_version' => '4.1.31',
            'version' => '4.1.31.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/codeception',
            'aliases' => array(),
            'reference' => '15524571ae0686a7facc2eb1f40f600e5bbce9e5',
            'dev_requirement' => true,
        ),
        'codeception/lib-asserts' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-asserts',
            'aliases' => array(),
            'reference' => 'df9c8346722ddde4a20e6372073c09c8df87c296',
            'dev_requirement' => true,
        ),
        'codeception/module-asserts' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-asserts',
            'aliases' => array(),
            'reference' => '313673c35de00ad337d3b5f895a1998695d3b537',
            'dev_requirement' => true,
        ),
        'codeception/module-db' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-db',
            'aliases' => array(),
            'reference' => '024505fff8faf6825478003151ad97c0fe46a942',
            'dev_requirement' => true,
        ),
        'codeception/phpunit-wrapper' => array(
            'pretty_version' => '9.0.7',
            'version' => '9.0.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/phpunit-wrapper',
            'aliases' => array(),
            'reference' => '7d6b1a5ea4ed28d010e5d36b993db813eb49710b',
            'dev_requirement' => true,
        ),
        'codeception/stub' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/stub',
            'aliases' => array(),
            'reference' => '18a148dacd293fc7b044042f5aa63a82b08bff5d',
            'dev_requirement' => true,
        ),
        'codegyre/robo' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '< 1.0',
            ),
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'reference' => '4c679186f2aca4ab6a0f1b0b9cf9252decb44d0b',
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'reference' => '647490bbcaf7fc4891c58f47b825eb99d19c377a',
            'dev_requirement' => true,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '1.4.6',
            'version' => '1.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'reference' => 'f27e06cd9675801df441b3656569b328e04aa37c',
            'dev_requirement' => true,
        ),
        'consolidation/annotated-command' => array(
            'pretty_version' => '2.12.2',
            'version' => '2.12.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/annotated-command',
            'aliases' => array(),
            'reference' => '2472a23610cba1d86dcb783a81a21259473b059e',
            'dev_requirement' => false,
        ),
        'consolidation/config' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/config',
            'aliases' => array(),
            'reference' => 'cac1279bae7efb5c7fb2ca4c3ba4b8eb741a96c1',
            'dev_requirement' => false,
        ),
        'consolidation/log' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/log',
            'aliases' => array(),
            'reference' => 'b2e887325ee90abc96b0a8b7b474cd9e7c896e3a',
            'dev_requirement' => false,
        ),
        'consolidation/output-formatters' => array(
            'pretty_version' => '3.5.1',
            'version' => '3.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/output-formatters',
            'aliases' => array(),
            'reference' => '0d38f13051ef05c223a2bb8e962d668e24785196',
            'dev_requirement' => false,
        ),
        'consolidation/robo' => array(
            'pretty_version' => '2.0.0-alpha1',
            'version' => '2.0.0.0-alpha1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/robo',
            'aliases' => array(),
            'reference' => '9877c6e327696d11317a156fd13453f12c6e8b4d',
            'dev_requirement' => false,
        ),
        'consolidation/self-update' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/self-update',
            'aliases' => array(),
            'reference' => 'dba6b2c0708f20fa3ba8008a2353b637578849b4',
            'dev_requirement' => false,
        ),
        'container-interop/container-interop' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../container-interop/container-interop',
            'aliases' => array(),
            'reference' => '79cbf1341c22ec75643d841642dd5d6acd83bdb8',
            'dev_requirement' => false,
        ),
        'container-interop/container-interop-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.2',
            ),
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'reference' => '3fbd874921ab2c041e899d044585a2ab9795df8a',
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.13.2',
            'version' => '1.13.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'reference' => '5b668aef16090008790395c02c893b1ba13f7e08',
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '1.12.1',
            'version' => '1.12.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'reference' => '4cf401d14df219fa6f38b671f5493449151c9ad8',
            'dev_requirement' => true,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => '10dcfce151b967d20fde1b34ae6640712c3891bc',
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'dev_requirement' => false,
        ),
        'erusev/parsedown' => array(
            'pretty_version' => '1.7.4',
            'version' => '1.7.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../erusev/parsedown',
            'aliases' => array(),
            'reference' => 'cb17b6477dfff935958ba01325f2e8a2bfa6dab3',
            'dev_requirement' => false,
        ),
        'evenement/evenement' => array(
            'pretty_version' => 'v3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../evenement/evenement',
            'aliases' => array(),
            'reference' => '531bfb9d15f8aa57454f5f0285b18bec903b8fb7',
            'dev_requirement' => false,
        ),
        'fabpot/goutte' => array(
            'pretty_version' => 'v3.3.1',
            'version' => '3.3.1.0',
            'type' => 'application',
            'install_path' => __DIR__ . '/../fabpot/goutte',
            'aliases' => array(),
            'reference' => '80a23b64f44d54dd571d114c473d9d7e9ed84ca5',
            'dev_requirement' => false,
        ),
        'felixfbecker/advanced-json-rpc' => array(
            'pretty_version' => 'v3.2.1',
            'version' => '3.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../felixfbecker/advanced-json-rpc',
            'aliases' => array(),
            'reference' => 'b5f37dbff9a8ad360ca341f3240dc1c168b45447',
            'dev_requirement' => true,
        ),
        'fig/http-message-util' => array(
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fig/http-message-util',
            'aliases' => array(),
            'reference' => '9d94dc0154230ac39e5bf89398b324a86f63f765',
            'dev_requirement' => false,
        ),
        'filp/whoops' => array(
            'pretty_version' => '2.14.5',
            'version' => '2.14.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../filp/whoops',
            'aliases' => array(),
            'reference' => 'a63e5e8f26ebbebf8ed3c5c691637325512eb0dc',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v6.2.0',
            'version' => '6.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => 'd28e6df83830252650da4623c78aaaf98fb385f3',
            'dev_requirement' => false,
        ),
        'fluffy/php-eureka-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fluffy/php-eureka-client',
            'aliases' => array(),
            'reference' => 'c6ee2d761161a5cb9aabbccde9e7fbf4d65a5d65',
            'dev_requirement' => false,
        ),
        'gmostafa/php-graphql-client' => array(
            'pretty_version' => 'v0.3.5',
            'version' => '0.3.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gmostafa/php-graphql-client',
            'aliases' => array(),
            'reference' => '1773a9ea01c8e77fe24908b12485804b886ff922',
            'dev_requirement' => false,
        ),
        'goaop/framework' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../goaop/framework',
            'aliases' => array(),
            'reference' => '596fcaefc18dfc4e3982b3ee552b0a3ceca9a8b1',
            'dev_requirement' => true,
        ),
        'goaop/parser-reflection' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../goaop/parser-reflection',
            'aliases' => array(),
            'reference' => 'c06ae32c4f5664dbd5829ab417485929eded0657',
            'dev_requirement' => true,
        ),
        'google/auth' => array(
            'pretty_version' => 'v1.21.0',
            'version' => '1.21.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/auth',
            'aliases' => array(),
            'reference' => '73392bad2eb6852eea9084b6bbdec752515cb849',
            'dev_requirement' => false,
        ),
        'google/cloud-core' => array(
            'pretty_version' => 'v1.45.0',
            'version' => '1.45.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/cloud-core',
            'aliases' => array(),
            'reference' => '28181b5ec2d40e9c9cdf2085096b33bac1f237fd',
            'dev_requirement' => false,
        ),
        'google/cloud-storage' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/cloud-storage',
            'aliases' => array(),
            'reference' => '51edfafd86ca3fc71e542a16961fb35bd59d7186',
            'dev_requirement' => false,
        ),
        'google/crc32' => array(
            'pretty_version' => 'v0.1.0',
            'version' => '0.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/crc32',
            'aliases' => array(),
            'reference' => 'a8525f0dea6fca1893e1bae2f6e804c5f7d007fb',
            'dev_requirement' => false,
        ),
        'grasmash/expander' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/expander',
            'aliases' => array(),
            'reference' => '95d6037344a4be1dd5f8e0b0b2571a28c397578f',
            'dev_requirement' => false,
        ),
        'grasmash/yaml-expander' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/yaml-expander',
            'aliases' => array(),
            'reference' => '3f0f6001ae707a24f4d9733958d77d92bf9693b1',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.5',
            'version' => '6.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '9d4290de1cfd701f38099ef7e183b64b4b7b0c5e',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'fe752aedc9fd8fcca3fe7ad05d419d32998a06da',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.5',
            'version' => '1.8.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '337e3ad8e5716c15f9657bd214d16cc5e69df268',
            'dev_requirement' => false,
        ),
        'jakubledl/dissect' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakubledl/dissect',
            'aliases' => array(),
            'reference' => 'd3a391de31e45a247e95cef6cf58a91c05af67c4',
            'dev_requirement' => true,
        ),
        'jumbojett/openid-connect-php' => array(
            'pretty_version' => 'v0.9.6',
            'version' => '0.9.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jumbojett/openid-connect-php',
            'aliases' => array(),
            'reference' => '5b0b423d5db7702012415b9071c41f665e674bf5',
            'dev_requirement' => false,
        ),
        'kreait/clock' => array(
            'pretty_version' => '1.2',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kreait/clock',
            'aliases' => array(),
            'reference' => '49e103382ca36cb2bc2e86ff3b8d11d44d0e0b31',
            'dev_requirement' => false,
        ),
        'kreait/firebase-php' => array(
            'pretty_version' => '5.26.2',
            'version' => '5.26.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kreait/firebase-php',
            'aliases' => array(),
            'reference' => 'da0e60f299eb591d5de741b51edb9350a40a8a6b',
            'dev_requirement' => false,
        ),
        'kreait/firebase-tokens' => array(
            'pretty_version' => '1.16.1',
            'version' => '1.16.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kreait/firebase-tokens',
            'aliases' => array(),
            'reference' => '595ad06cb5f75c188d8fbfdefc9078c3ec8aa5e8',
            'dev_requirement' => false,
        ),
        'laminas/laminas-code' => array(
            'pretty_version' => '4.5.1',
            'version' => '4.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-code',
            'aliases' => array(),
            'reference' => '6fd96d4d913571a2cd056a27b123fa28cb90ac4e',
            'dev_requirement' => true,
        ),
        'laravel/serializable-closure' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/serializable-closure',
            'aliases' => array(),
            'reference' => '9e4b005daa20b0c161f3845040046dc9ddc1d74e',
            'dev_requirement' => false,
        ),
        'lcobucci/clock' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/clock',
            'aliases' => array(),
            'reference' => '353d83fe2e6ae95745b16b3d911813df6a05bfb3',
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '4.1.5',
            'version' => '4.1.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'reference' => 'fe2d89f2eaa7087af4aa166c6f480ef04e000582',
            'dev_requirement' => false,
        ),
        'league/container' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'reference' => '8438dc47a0674e3378bcce893a0a04d79a2c22b3',
            'dev_requirement' => false,
        ),
        'microsoft/tolerant-php-parser' => array(
            'pretty_version' => 'v0.0.17',
            'version' => '0.0.17.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../microsoft/tolerant-php-parser',
            'aliases' => array(),
            'reference' => '89386de8dec9c004c8ea832692e236c92f34b542',
            'dev_requirement' => true,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '247918972acd74356b0a91dfaa5adcaec069b6c0',
            'dev_requirement' => false,
        ),
        'mpdf/mpdf' => array(
            'pretty_version' => 'v8.0.4',
            'version' => '8.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/mpdf',
            'aliases' => array(),
            'reference' => 'd3147a0d790b6d11936fd9c73fa31a7ed45e3f6f',
            'dev_requirement' => false,
        ),
        'mtdowling/jmespath.php' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/jmespath.php',
            'aliases' => array(),
            'reference' => '9b87907a81b87bc76d19a7fb2d61e61486ee9edb',
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'reference' => '14daed4296fae74d9e3201d2c4925d1acb7aa614',
            'dev_requirement' => false,
        ),
        'n98/junit-xml' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../n98/junit-xml',
            'aliases' => array(),
            'reference' => '7df0dbaf413fcaa1a63ffbcef18654e7a4cceb46',
            'dev_requirement' => true,
        ),
        'netresearch/jsonmapper' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../netresearch/jsonmapper',
            'aliases' => array(),
            'reference' => '8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d',
            'dev_requirement' => true,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.13.2',
            'version' => '4.13.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '210577fe3cf7badcc5814d99455df46564f3c077',
            'dev_requirement' => true,
        ),
        'ocramius/package-versions' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../ocramius/package-versions',
            'aliases' => array(),
            'reference' => '94c9d42a466c57f91390cdd49c81313264f49d85',
            'dev_requirement' => true,
        ),
        'orno/di' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'overtrue/phplint' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../overtrue/phplint',
            'aliases' => array(),
            'reference' => '05bef7df401f8e250436bbb008c25d1b344c0e5e',
            'dev_requirement' => true,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.99',
            'version' => '9.99.99.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '84b4dfb120c6f9b4ff7b3685f9b8f1aa365a0c95',
            'dev_requirement' => false,
        ),
        'phan/phan' => array(
            'pretty_version' => '1.3.5',
            'version' => '1.3.5.0',
            'type' => 'project',
            'install_path' => __DIR__ . '/../phan/phan',
            'aliases' => array(),
            'reference' => 'f872949b366d84bd9ce79d8b0ea991edbe258377',
            'dev_requirement' => true,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'reference' => '97803eca37d319dfa7826cc2437fc020857acb53',
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'dev_requirement' => true,
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '~1.0',
            ),
        ),
        'php2wsdl/php2wsdl' => array(
            'pretty_version' => '0.6.1',
            'version' => '0.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php2wsdl/php2wsdl',
            'aliases' => array(),
            'reference' => '37c15cdc4cdd15363faf151dc0121ac5595fc513',
            'dev_requirement' => false,
        ),
        'phpcompatibility/php-compatibility' => array(
            'pretty_version' => '9.3.5',
            'version' => '9.3.5.0',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../phpcompatibility/php-compatibility',
            'aliases' => array(),
            'reference' => '9fb324479acf6f39452e0655d2429cc0d3914243',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.3.0',
            'version' => '5.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => '622548b623e81ca6d78b721c5e029f4ce664f170',
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => '77a32518733312af16a44300404e945338981de3',
            'dev_requirement' => true,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.37',
            'version' => '2.0.37.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => 'c812fbb4d6b4d7f30235ab7298a12f09ba13b37c',
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.15.0',
            'version' => '1.15.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'reference' => 'bbcd7380b0ebf3961ee21409db7b38bc31d69a13',
            'dev_requirement' => true,
        ),
        'phpstan/phpstan' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpstan',
            'aliases' => array(),
            'reference' => '0d13a99513182e521271d46bde8f28caa4f84d97',
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '9.2.15',
            'version' => '9.2.15.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => '2e9da11878c4202f97915c1cb4bb1ca318a63f5f',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '3.0.6',
            'version' => '3.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => 'cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf',
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'reference' => '5a10147d0aaf65b58940a0b72f71c9ac0423cc67',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '9.5.20',
            'version' => '9.5.20.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => '12bc8879fb65aef2138b26fc633cb1e3620cffba',
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '~1.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
                1 => '~1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0 || 2.0.0 || 3.0.0',
                1 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'react/event-loop' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/event-loop',
            'aliases' => array(),
            'reference' => '187fb56f46d424afb6ec4ad089269c72eec2e137',
            'dev_requirement' => false,
        ),
        'react/zmq' => array(
            'pretty_version' => 'v0.4.0',
            'version' => '0.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/zmq',
            'aliases' => array(),
            'reference' => '13dec0bd2397adcc5d6aa54c8d7f0982fba66f39',
            'dev_requirement' => false,
        ),
        'riverline/multipart-parser' => array(
            'pretty_version' => '2.0.9',
            'version' => '2.0.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../riverline/multipart-parser',
            'aliases' => array(),
            'reference' => 'ebba10245b5a6e03a673ff52c547d05029caedab',
            'dev_requirement' => false,
        ),
        'rize/uri-template' => array(
            'pretty_version' => '0.3.4',
            'version' => '0.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rize/uri-template',
            'aliases' => array(),
            'reference' => '2a874863c48d643b9e2e254ab288ec203060a0b8',
            'dev_requirement' => false,
        ),
        'sabre/event' => array(
            'pretty_version' => '5.1.4',
            'version' => '5.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabre/event',
            'aliases' => array(),
            'reference' => 'd7da22897125d34d7eddf7977758191c06a74497',
            'dev_requirement' => true,
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'reference' => '442e7c7e687e42adc03470c7b668bc4b2402c0b2',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '1.0.8',
            'version' => '1.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'reference' => '1fc9f64c0927627ef78ba436c9b17d967e68e120',
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'reference' => 'ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5',
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'reference' => '55f4261989e546dc112258c7a75935a81a7ce382',
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'reference' => '739b35e53379900cc9ac327b2147867b8b6efd88',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'reference' => '3461e3fccc7cfdfc2720be910d3bd73c69be590d',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '5.1.4',
            'version' => '5.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'reference' => '1b5dff7bb151a4db11d49d90e5408e4e938270f7',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'reference' => '65e8b7db476c5dd267e65eea9cab77584d3cfff9',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '5.0.5',
            'version' => '5.0.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'reference' => '0ca8db5a5fc9c8646244e629625ac486fa286bf2',
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'reference' => 'c1c2e997aa3146983ed888ad08b15470a2e22ecc',
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'reference' => '5c9eeac41b290a3712d88851518825ad78f45c71',
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'reference' => 'b4f479ebdbf63ac605d183ece17d8d7fe49c15c7',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'reference' => 'cd9d8cf3c5804de4341c283ed787f099f5506172',
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'reference' => '0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8',
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'reference' => 'b233b84bc4465aff7b57cf1c4bc75c86d00d6dad',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'reference' => 'c6c1022351a901512170118436c764e473f6de8c',
            'dev_requirement' => true,
        ),
        'setasign/fpdf' => array(
            'pretty_version' => '1.8.4',
            'version' => '1.8.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdf',
            'aliases' => array(),
            'reference' => 'b0ddd9c5b98ced8230ef38534f6f3c17308a7974',
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'reference' => 'ff7e43e07abb97feb4a1cceaf72d75ce0e175ca0',
            'dev_requirement' => false,
        ),
        'spatie/async' => array(
            'pretty_version' => '1.5.4',
            'version' => '1.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/async',
            'aliases' => array(),
            'reference' => '0b16f717a8ccaf78f6b66934567a789978734490',
            'dev_requirement' => false,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.6.2',
            'version' => '3.6.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'reference' => '5e4e71592f69da17871dba6e80dd51bce74a351a',
            'dev_requirement' => true,
        ),
        'sserbin/twig-linter' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sserbin/twig-linter',
            'aliases' => array(),
            'reference' => '6928441b55052ea9f766dcfa6ccf47942eff71c3',
            'dev_requirement' => true,
        ),
        'stella-maris/clock' => array(
            'pretty_version' => '0.1.4',
            'version' => '0.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stella-maris/clock',
            'aliases' => array(),
            'reference' => '8a0a967896df4c63417385dc69328a0aec84d9cf',
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'reference' => '18e73179c6a33d520de1b644941eba108dd811ad',
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.12',
            ),
        ),
        'symfony/console' => array(
            'pretty_version' => 'v4.2.12',
            'version' => '4.2.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => 'fc2e274aade6567a750551942094b2145ade9b6c',
            'dev_requirement' => false,
        ),
        'symfony/contracts' => array(
            'pretty_version' => 'v1.1.12',
            'version' => '1.1.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/contracts',
            'aliases' => array(),
            'reference' => '5236c15b24aeeecee4b9c6ad4b22f6331f2cbdcb',
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => 'b0a190285cd95cb019237851205b8140ef6e368e',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.1',
            'version' => '2.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v5.4.6',
            'version' => '5.4.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'reference' => 'c0bda97480d96337bd3866026159a8b358665457',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => '31fde73757b6bad247c54597beef974919ec6860',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.12',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v4.4.39',
            'version' => '4.4.39.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => '72a5b35fecaa670b13954e6eaf414acbe2a67b35',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v4.4.41',
            'version' => '4.4.41.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '40790bdf293b462798882ef6da72bb49a4a6633a',
            'dev_requirement' => false,
        ),
        'symfony/http-client-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.12',
            ),
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '30885182c981ab175d4d034db0f6f469898070ab',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '749045c69efb97c70d25d7463abba812e91f3a44',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '0abb51d2f102e00a4eefcf46ba7fec406d245825',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '9a142215a36a3888e30d0a9eeea9766764e96976',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'cc5db0e22b3cb4111010e48785a97f670b350ca5',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '4407588e0d3f1f52efb65fbe92babe41f37fe50c',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => '5de4ba2d41b15f9bd0e19b2ab9674135813ec98f',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v4.4.41',
            'version' => '4.4.41.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => '9eedd60225506d56e42210a70c21bb80ca8456ce',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.12',
            ),
        ),
        'symfony/translation-contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.1.12',
            ),
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v4.4.37',
            'version' => '4.4.37.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => 'd7f637cc0f0cc14beb0984f2bb50da560b271311',
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'dev_requirement' => true,
        ),
        'trf4/eproc' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'app',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '9a9580fa1c0429ed45b06dc8f6aeaa936949c277',
            'dev_requirement' => false,
        ),
        'trf4/infra' => array(
            'pretty_version' => '1.603.2',
            'version' => '1.603.2.0',
            'type' => 'framework',
            'install_path' => __DIR__ . '/../trf4/infra',
            'aliases' => array(),
            'reference' => '303da4f0e23b25f375ea59961b79ad27f1f8d7de',
            'dev_requirement' => false,
        ),
        'trf4/pdpj-cabecalho-processual' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../trf4/pdpj-cabecalho-processual',
            'aliases' => array(),
            'reference' => 'a78db3558ca62db6f2dc60da48b747e45cc370b1',
            'dev_requirement' => false,
        ),
        'trf4/pdpj-consulta-criminal' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../trf4/pdpj-consulta-criminal',
            'aliases' => array(),
            'reference' => 'f90c133b8e0d17c8fe5a606e4a2d29a319fd2950',
            'dev_requirement' => false,
        ),
        'trf4/pdpj-enderecos' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../trf4/pdpj-enderecos',
            'aliases' => array(),
            'reference' => '7ab3ea52d5315cd39099a44d01cce14b6235729f',
            'dev_requirement' => false,
        ),
        'trf4/pdpj-notificacao' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../trf4/pdpj-notificacao',
            'aliases' => array(),
            'reference' => 'f6c750c54463b80baf6b82d711baf33991691d8c',
            'dev_requirement' => false,
        ),
        'trf4/pdpj-pessoa' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../trf4/pdpj-pessoa',
            'aliases' => array(),
            'reference' => '208ca6c9ea4054ced29dbff37c8d30bdf3593fa4',
            'dev_requirement' => false,
        ),
        'trf4/pdpj-tpu' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../trf4/pdpj-tpu',
            'aliases' => array(),
            'reference' => '48f3d9cf0e885007d023008b56fd02282b6980fb',
            'dev_requirement' => false,
        ),
        'trf4/ui' => array(
            'pretty_version' => '0.10.0',
            'version' => '0.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../trf4/ui',
            'aliases' => array(),
            'reference' => '932620b7ea763fd44b74a69687efc99fecc4c929',
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'reference' => 'ed19f4bf9d19c4ef920b5d8243910bd32e85b9ba',
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v2.6.9',
            'version' => '2.6.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'reference' => '2e93cc98e2e8e869f8d9cfa61bb3a99ba4fc4141',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '6964c76c7804814a842473e0c8fd15bab0f18e25',
            'dev_requirement' => true,
        ),
        'webonyx/graphql-php' => array(
            'pretty_version' => 'v0.13.9',
            'version' => '0.13.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webonyx/graphql-php',
            'aliases' => array(),
            'reference' => 'd9a94fddcad0a35d4bced212b8a44ad1bc59bdf3',
            'dev_requirement' => false,
        ),
        'windwalker/application' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/authentication' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/authorisation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/compare' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/crypt' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/data' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/datamapper' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/di' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/dom' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/edge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/environment' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/event' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/filter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/form' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/framework' => array(
            'pretty_version' => '3.5.23',
            'version' => '3.5.23.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../windwalker/framework',
            'aliases' => array(),
            'reference' => '534a0efcb95425f6715c5667e9d7a8134200249f',
            'dev_requirement' => false,
        ),
        'windwalker/html' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/io' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/language' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/loader' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/middleware' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/profiler' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/query' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/record' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/renderer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/router' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/string' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/structure' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/test' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/uri' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/utilities' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'windwalker/validator' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.5.23',
            ),
        ),
        'wingu/reflection' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wingu/reflection',
            'aliases' => array(),
            'reference' => '604637061ccc12da7f700865ccb9058e648181dd',
            'dev_requirement' => false,
        ),
    ),
);
